name: Get latest release version
on:
  schedule:
    - cron:  '20 11,23 * * *'
    
  workflow_dispatch: 
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          super_secret: ${{ secrets.REPO_SCOPED_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/neovide/neovide/releases/latest | \
          jq -r ".tag_name" > release-versions/latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'nosqrt'
          git config --global user.email 'nosqrt@outlook.com'
          git commit -am "New release version"
          git push
